rm -rf "/Users/$USER/Library/Caches"
rm -rf "/Users/$USER/Library/Containers/"
rm -rf "/Users/$USER/Library/Application Support/Code/User/workspaceStorage"
rm -rf "/Users/$USER/Library/Application Support/Code/Cache"
rm -rf "/Users/$USER/Library/Application Support/Code/CachedData"
rm -rf "/Users/$USER/Library/Application Support/Code/Code Cache"
rm -rf "/Users/$USER/Library/Application Support/Code/CachedExtensions"
rm -rf "/Users/$USER/Library/Application Support/Code/CachedExtensionVSIXs"
rm -rf "/Users/$USER/Library/Application Support/Slack/Service Worker"
rm -rf "/Users/$USER/Library/Application Support/Slack/Cache"
rm -rf "/Users/$USER/Library/Application Support/Slack/CachedData"
rm -rf "/Users/$USER/Library/Application Support/Slack/Service Worker/CacheStorage"
rm -rf "/Users/$USER/Library/Application Support/Slack/Service Worker/ScriptCache"
